- name: instalation for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: install postgresql
      package: 
        name: postgresql
        state: present
    - name: install psycopg
      package: 
        name: postgresql-contrib
        state: present
    - name: install libpq-dev
      package:
        name: libpq-dev
        state: present

- name: db init
  hosts: host01
  gather_facts: false
  tasks:
    - name: copy
      copy:
        src: "{{ hostvars[inventory_hostname]['dir'] }}/init.sql"
        dest: /tmp/init.sql
        mode: '0644'
    - name: change owner
      command: chown postgres:postgres /tmp/init.sql
    - name: temp_db
      replace:
        path: /tmp/init.sql
        regexp: "temp_dbname"
        replace: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
    - name: temp_repluser
      replace:
        path: /tmp/init.sql
        regexp: "temp_repluser"
        replace: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
    - name: temp_replpassword
      replace:
        path: /tmp/init.sql
        regexp: "temp_replpassword"
        replace: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
    - name: temp_postgresuser
      replace:
        path: /tmp/init.sql
        regexp: "temp_postgresuser"
        replace: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
    - name: temp_postgrespassword
      replace:
        path: /tmp/init.sql
        regexp: "temp_postgrespassword"
        replace: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
    - name: init.sql
      command: psql -a -f /tmp/init.sql
      become: true
      become_user: postgres

- name: repl config
  hosts: host01
  gather_facts: false
  tasks:
    - name: add to conf file
      blockinfile:
        path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/postgresql.conf"
        block: |
          listen_addresses = '*'
          port=5432
          wal_level=replica
          wal_log_hints=on
          hot_standby=on
          max_wal_senders=10
          max_replication_slots=10
          hot_standby_feedback=on
          log_replication_commands=on
    - name: pg_hba conf
      blockinfile:
        path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/pg_hba.conf"
        block: | 
          host replication {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} {{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}/24 md5
          host all all 0.0.0.0/0 password
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
      
- name: slave config and init
  hosts: host02
  gather_facts: false
  tasks:
    - name: delete directory
      command: rm -rf /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/
    - name: pg_basebackup
      command: pg_basebackup -h {{ hostvars[inventory_hostname]['DB_HOST'] }} -D /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/ -U {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} -vP -w
      environment: 
        PGPASSWORD: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
        become_user: postgres
    - name: chown
      command: chown -R postgres:postgres /var/lib/postgresql/
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted

- name: python bot
  hosts: host01
  gather_facts: false
  tasks:
    - name: update
      command: apt update 
    - name: install python3-dev
      package:
        name: python3-dev
        state: present
    - name: install build-essential
      package:
        name: build-essential
        state: present
    - name: install pip
      package:
        name: pip
        state: present
    - name: install git
      package:
        name: git
        state: present
    - name: mkdir
      command: mkdir -p "{{ hostvars[inventory_hostname]['dir'] }}/repo"
    - name: git clone
      git:
        repo: https://github.com/jebulya/DEVOPS.git
        dest: "{{ hostvars[inventory_hostname]['dir'] }}/repo"
        version: main
    - name: pip install
      pip: 
        requirements: "{{ hostvars[inventory_hostname]['dir'] }}/repo/requirements.txt"
    - name: mkdir logs
      command: mkdir -p "{{ hostvars[inventory_hostname]['dir'] }}/../logs"
    - name: run python bot
      command: python3 "{{ hostvars[inventory_hostname]['dir'] }}/repo/bot.py"
      environment:
        TOKEN: "{{ hostvars[inventory_hostname]['TOKEN'] }}"
        RM_HOST: "{{ hostvars[inventory_hostname]['RM_HOST'] }}"
        RM_PORT: "{{ hostvars[inventory_hostname]['RM_PORT'] }}"
        RM_USER: "{{ hostvars[inventory_hostname]['RM_USER'] }}"
        RM_PASSWORD: "{{ hostvars[inventory_hostname]['RM_PASSWORD'] }}"
        DB_HOST: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        DB_PORT: "{{ hostvars[inventory_hostname]['DB_PORT'] }}"
        DB_USER: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
        DB_PASSWORD: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"
        DB_DATABASE: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
        PG_VERSION: "{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}"
    
      
